Dockerize it
WHOIGit/django-ninja-react-example pull request #6
Opened 2024-08-21 07:20 UTC by cpwallah

2024-08-21 13:24 UTC, joefutrelle requested changes
Thanks for the PR! I see numerous issues with it that will require some restructuring.

2024-08-21 13:24 UTC, joefutrelle commented on ninjareact/Dockerfile
> +RUN python manage.py collectstatic --noinput
it doesn't make sense to run these commands at build time--these steps need to be taken at deploy time.

2024-08-21 13:24 UTC, joefutrelle commented on docker-compose.yml
> +      - app_network
There should not be a frontend service--the frontend is served by Django.

2024-08-21 13:24 UTC, joefutrelle commented on ninjareact/frontend/Dockerfile
There should be no frontend service (see comment on compose file)

2024-08-21 13:24 UTC, joefutrelle commented on docker-compose.yml
> +      - ./ninjareact:/app
application code is included in the Docker image  by your Dockerfile and should not be mapped into the container at runtime.

2024-08-21 13:27 UTC, joefutrelle commented
@cpwallah I think there are a few ways we could complete this task:

1. You make the requested changes and I will review them;
1. I take over this task and commit to this branch;
1. I take over this task on a new branch / PR

My preference is the latter option given the amount of restructuring required in this PR.

2024-08-21 16:49 UTC, cpwallah commented
i will try to resolve these issue

2024-08-22 14:41 UTC, joefutrelle commented
@cpwallah I'm also bringing in a second reviewer, @mike-kaimika

2024-08-22 15:30 UTC, cpwallah commented
okay @joefutrelle as i am new in using docker would you guide me if needed?

2024-08-22 16:39 UTC, joefutrelle commented
> okay @joefutrelle as i am new in using docker would you guide me if needed?

If you're new to using Docker then you may want to find a project outside of this organization that you can contribute to. If you're interested in open-source development and Docker, then feel free to follow the linked issue #5 which will be associated with an upcoming PR from me or @mike-kaimika completing the work.

2024-08-22 16:39 UTC, closed without merging

2024-08-22 17:53 UTC, cpwallah commented
hello plz repopen  it @joefutrelle

2024-08-22 17:53 UTC, cpwallah commented
now everything is running fine as i have set up it